name: setel_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  easy_search_bar: ^2.5.0
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.6
  image_picker: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  line_awesome_flutter: ^2.0.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gku.jpg
    - assets/msu.jpg
    - assets/oplib.jpg
    - assets/tult.jpg
    - assets/setel.png
    - assets/circle.png
    - assets/crsel-1.jpg
    - assets/crsel-2.jpg
    - assets/crsel-3.jpg
    - assets/check.png